### ISSUE TITLE
How can I set OutboundMessageMapper?

### ISSUE THREAD

**Issue by DesFieldCorbett** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#101]
Hi,

I am trying to add custom headers to a Spring Cloud Stream Kinesis message. I have tried setting:
spring.cloud.stream.bindings.mystream.producer.header-mode=embeddedHeaders
and
spring.cloud.stream.kinesis.binder.headers="correlationId", "sequenceSize", "sequenceNumber", "contentType", "originalContentType", "MY-Header"

I also create my message with Headers using MessageBuilder

But I can see that when the message is sent my headers are replaced by the standard AWS headers.

Working through the code I can see that my headers are never added to the message in KinesisMessageHandler due to embeddedHeadersMapper being null.

I have read I need to set a EmbeddedJsonHeadersMessageMapper but I cannot see how, and the setEmbeddedHeadersMapper never seems to be called.

Thanks for your help,
des

**Comment by artembilan** [comment]
The `embeddedHeadersMapper` is not used in case of Spring Cloud Stream.
The logic is look like this:
```
((SubscribableChannel) outputChannel)
				.subscribe(new SendingHandler(producerMessageHandler,
						HeaderMode.embeddedHeaders
								.equals(producerProperties.getHeaderMode()),
						this.headersToEmbed, useNativeEncoding(producerProperties)));
```

So, there is some sending wrapper around the target `KinesisMessageHandler`, which builds a `Message` to produce with embedded headers.

Something else might going on in your case. We have a test case which covers custom headers as well: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/spring-cloud-stream-binder-kinesis/src/test/java/org/springframework/cloud/stream/binder/kinesis/KinesisBinderProcessorTests.java#L75

May your problem that you have each of those headers wrapped into quotes meanwhile you send a message without quotes...
How about to have a config like this:
```
spring.cloud.stream.kinesis.binder.headers=MY-Header
```

You don't need to iterate all other headers since they are standard and merged with your custom anyway:
```
String[] combinedHeadersToMap = Arrays.copyOfRange(
					BinderHeaders.STANDARD_HEADERS, 0,
					BinderHeaders.STANDARD_HEADERS.length
							+ configurationProperties.getHeaders().length);
			System.arraycopy(configurationProperties.getHeaders(), 0,
					combinedHeadersToMap, BinderHeaders.STANDARD_HEADERS.length,
					configurationProperties.getHeaders().length);
			return combinedHeadersToMap;
```

**Comment by DesFieldCorbett** [comment]
Thanks so much for your help. It seems to have been the quotes around the header name - I  simply copied from the Overview document.

However I did see something odd in my IDE (IntelliJ Ultimate 2019.1) when setting header-mode- IntelliJ autosuggested embeddedheaders instead of embeddedHeaders. - it seems though that you do not need to set this anyway.

**Comment by artembilan** [comment]
Right, you do not need to set it. AWS Kinesis doesn't have `headers` concept, so to meet our Spring Cloud Stream compatibility with other binders in between, we always set `embeddedHeaders` for this binder.
