### ISSUE TITLE
Consumer-Group Behavior Question

### ISSUE THREAD

**Issue by chiku80** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#103]
am using a `consumer-group` of 5 consumers. Each consumer is an ec2 instance consuming from a kinesis queue that has 5 shards. Each ec2 instance is uing the same consumer-group name and using TRIM_HORIZON. I have set the `spring.cloud.stream.bindings.<channelName>.consumer.concurrency = 1`  on each each ec2 instance. Will this not force each ec2 instance to consume  from 1 shard ? In other words each instance should be consuming one message concurrently..right?

However, the behavior i am seeing is that only one of the ec2 Instances is consuming messages from the kinesis queue. And the other instances are just sitting there doing nothing. Also, The instance that is consuming messages is only consuming 1 message at a time (which makes sense cause concurrency is set to 1). 

Is what I have described the expected behavior? Is there a way to distribute shard iterators over instances in the same consumer group?

**Comment by chiku80** [comment]
I am using a `consumer-group` of 5 consumers. Each consumer is an ec2 instance consuming from a kinesis queue that has 5 shards. Each ec2 instance is uing the same consumer-group name and using TRIM_HORIZON. I have set the `spring.cloud.stream.bindings.<channelName>.consumer.concurrency = 1`  on each each ec2 instance. Will this not force each ec2 instance to consume  from 1 shard ? In other words each instance should be consuming one message concurrently..right?

However, the behavior i am seeing is that only one of the ec2 Instances is consuming messages from the kinesis queue. And the other instances are just sitting there doing nothing. Also, The instance that is consuming messages is only consuming 1 message at a time (which makes sense cause concurrency is set to 1). 

Is what I have described the expected behavior? Is there a way to distribute shard iterators over instances in the same consumer group?

**Comment by artembilan** [comment]
By default the `KinesisMessageDrivenChannelAdapter` is used with the `DynamoDbLockRegistry` to obtain an exclusive access to the shard. So, you are just not lucky that only one instance from your cluster is locking all the shards in that stream.

Starting with version `1.2` we have introduced `kplKclEnabled` option to use a Kinesis Client Library for consuming: https://spring.io/blog/2019/05/13/spring-integration-aws-2-2-ga-and-spring-cloud-stream-kinesis-binder-1-2-ga-available

This one has a different way to distribute shards in the cluster, so, might be the way for your requirements.

You are correct about `concurrency = 1`. This way only one thread is going to iterate over all the shards assigned to the  `KinesisMessageDrivenChannelAdapter`. That's why you see only one message at a time independently of the number of shards in this instance.

I'm considering this as a *question* and as answered.

Please, raise questions in the future on StackOverflow. You'll get a gain of the community in faster answer meanwhile here on GitHub it might not be a case that many people can see your problem.

Thanks for understanding!

**Comment by chiku80** [comment]
thankyou for the response artem! Will ask future questions on stack overflow.
