### ISSUE TITLE
AT_TIMESTAMP expected behavior for existing consumers

### ISSUE THREAD

**Issue by ywilkof** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#110]
I would like to consume again messages that have already been consumed, by setting the AT_TIMESTAMP iterator. I would expect the last checkpointed message to be updated upon consumer restart to a message around AT_TIMESTAMP value. 

The consumer picks up my configuration correctly: 

`2019-08-29 11:10:12.408 INFO 7 --- [ main] a.i.k.KinesisMessageDrivenChannelAdapter : started KinesisMessageDrivenChannelAdapter{shardOffsets=[KinesisShardOffset{iteratorType=AT_TIMESTAMP, sequenceNumber='null', timestamp=Mon Aug 26 16:00:00 UTC 2019, stream='kinesis-staging-Staging-AIS0PIK181JT', shard='shardId-000000000001', reset=false}, KinesisShardOffset{iteratorType=AT_TIMESTAMP, sequenceNumber='null', timestamp=Mon Aug 26 16:00:00 UTC 2019, stream='kinesis-staging-Staging-AIS0PIK181JT', shard='shardId-000000000000', reset=false}], consumerGroup='promo-codes'}
`

And afterwards

`
2019-08-29 11:10:53.416 INFO 7 --- [esis-consumer-1] a.i.k.KinesisMessageDrivenChannelAdapter : The [ShardConsumer{shardOffset=KinesisShardOffset{iteratorType=AT_TIMESTAMP, sequenceNumber='null', timestamp=Mon Aug 26 16:00:00 UTC 2019, stream='kinesis-staging-Staging-AIS0PIK181JT', shard='shardId-000000000000', reset=false}, state=NEW}] has been started.
`

However, looking at the last message checkpointed in the dynamo db table, it is still the latest consumed message (recent timestamp).  I print to the logs every consumed message and I see nothing printed. I checked and the stream is not empty, there are still unexpired messages after AT_TIMESTAMP value I am supplying. If the AT_TIMESTAMP works, then I would expect to see them printed. 
These support that the consumer do not actually go back in time.

Is it possible using the library for this? Am I missing some extra configuration?

Thanks!

**Comment by artembilan** [comment]
There is the logic like:
```
if (this.shardOffset.isReset()) {
	this.checkpointer.remove();
}
else {
	String checkpoint = this.checkpointer.getCheckpoint();
	if (checkpoint != null) {
		this.shardOffset.setSequenceNumber(checkpoint);
		this.shardOffset.setIteratorType(ShardIteratorType.AFTER_SEQUENCE_NUMBER);
	}
}
if (logger.isInfoEnabled() && this.state == ConsumerState.NEW) {
	logger.info("The [" + this + "] has been started.");
}
```

So, if `reset` flag is set (what is not your case and it is not possible currently with this project), we just remove the entry for the shard from the checkpoint store.
If it not true, then we try to obtain the latest sequence from the store. And, therefore, change the iterator type to the `sequence` one.

Since according your logs `KinesisShardOffset{iteratorType=AT_TIMESTAMP, sequenceNumber='null'` we don't do that it looks like there is nothing for the `shardId-000000000000` in the store. So, we just go and try to consume a shared from the timestamp like `Mon Aug 26 16:00:00 UTC 2019`. Not sure if that is what you expect, but indeed something is broken since you claim like something is there in the store for that shard.

Not sure how to help you because everything after `this.checkpointer.getCheckpoint()` returning `null` in the beginning does not make sense. Because we wouldn't have any values in the store for this shard afterwards as well...

**Comment by ywilkof** [comment]
Thank you for the quick response. It is indeed weird, as the checkpoint metadata is there.
At any case, I got the answer - If there is already a checkpoint, it will not go back in time, since we cannot control the reset flag. If this is correct, then this is a different behavior than with LATEST, where we will "reset" the checkpoint to the last message in the stream, even if we have a checkpoint for a previous message.

I managed to around this by forcing a reset, that is, by manually deleting the checkpoint from Dynamo.
