### ISSUE TITLE
How are exceptions handled when using manual checkpoint with KCL enabled?

### ISSUE THREAD

**Issue by v9ru** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#126]
I am using spring-cloud-stream-binder-kinesis (2.0.1.RELEASE) with Kcl Enabled and manual checkpoint mode.

When there is an error during processing the records (before I manually checkpointed), I am not getting the same batch when polling for the next time. Looks like this is checkpointed when there are issues.

What should I do if I don't want that to happen and my consumer should poll indefinitely until I fix the issue?

EDIT:
I got the following error
```
KclMessageDrivenChannelAdapter : Got an exception during sending a 'GenericMessage <payload, headers , etc>'.
Consider to use 'errorChannel' flow for the compensation logic.
```

What will happen if I use an errorChannel? Will the records get checkpointed and Do I have to handle the failed ones by consuming errorChannel?

**Comment by v9ru** [comment]
@artembilan can you please help me with this.

Only solution I can think of is to handle all Exceptions and don't checkpoint if I find an exception. But I don't think that's a good way. Can you suggest any alternatives?

**Comment by v9ru** [comment]
I just tried to catch all exceptions. Even then, it is going to the next records despite setting checkpoint mode to manual. Isn't that configuration used when KCL is enabled?

**Comment by v9ru** [comment]
Is it by any chance because of https://github.com/spring-projects/spring-integration-aws/blob/master/src/main/java/org/springframework/integration/aws/inbound/kinesis/KclMessageDrivenChannelAdapter.java#L502 ?

It is catching the exception but not throwing it again. And when there is an exception I am not checkpointing it too. So is KCL sending more records and then the method I marked with @StreamListener is getting triggered at which point I checkpoint the progress and hence I will lose the old records.

**Comment by artembilan** [comment]
>  I am not getting the same batch when polling for the next time.

That's not how Kinesis works. The checkpoint is fully not related to what the next iterator brings for you.
We need store a checkpoint for case of crash, so the next start would not consume the same records again, but from the point of check.

There is no re-delivery in Kinesis. You can stop your consumer, advance it to the appropriate sequence and start again to get the same records.
The Kiensis shard iterator doesn't expect rallback on error.

That's why we suggest something like compensation flow via error handling or retry logic in your application. Just because Kinesis by itself doesn't give us any (n)ack or transactions leveler for its records.

I consider this issue as out-of-scope and closing it in favor similar questions for the respective community.
