### ISSUE TITLE
Explore options to use kinesalite and dynalite for local integration tests

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#13]
As a developer, I'd like to study how to make use of "kinesalite" and "dynalite" for local development/integration tests. 

**Acceptance:**
- Document steps to integrate and make use of kinesalite and dynalite.
- Existing tests can run against the local instances of kinesalite and dynalite.

**Comment by artembilan** [comment]
This has been fixed in the Spring Integration AWS. See its README starting with: https://github.com/spring-projects/spring-integration-aws#metadata-store-for-amazon-dynamodb.

In addition this project provides already `LocalKinesisResource` implementation which works well.

See https://github.com/spring-projects/spring-integration-aws/issues/72 for more info.
