### ISSUE TITLE
can this binder produce in batch ?

### ISSUE THREAD

**Issue by hamid646** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#146]
Is it possible to have a `Function` that consumes in Batch and produces in batch? 

something like:

```
@Bean
 public Function<Message<List<Person>>,Message<List<Person>>> person() {
```
OR

```
@Bean
 public Function<Message<List<Person>>, PutRecordsRequest> person() {
```

Currently it only uses putRecord with is for a single record and there is also PutRecords.

**Comment by artembilan** [comment]
The `PutRecordsRequest` must work. See `KinesisMessageHandler`:

```
protected Future<?> handleMessageToAws(Message<?> message) {
if (message.getPayload() instanceof PutRecordsRequest) {
		AsyncHandler<PutRecordsRequest, PutRecordsResult> asyncHandler = obtainAsyncHandler(message,
					(PutRecordsRequest) message.getPayload());

		return this.amazonKinesis.putRecordsAsync((PutRecordsRequest) message.getPayload(), asyncHandler);
}
```

I think the `Message<List<Person>>` is iterated by Spring Cloud Stream internally and really produced records one by one.
Nevertheless it is not going to work with `KinesisMessageHandler` just because there is no `List` of payloads support and it is treated as a single record to send to Kinesis.

If you talk about a `KplMessageHandler`, then it indeed doesn't provide a single `PutRecordsRequest` call just because an underlying KPL doesn't support multi-record request.

**Comment by hamid646** [comment]
it worked, thanks - just needed to make two changes:

```spring.cloud.stream.kinesis.binder.auto-create-stream=false```

```
@Bean
public Function<Message<List< Person >>, Message<PutRecordsRequest>> person() {
```

**Comment by artembilan** [comment]
`use-native-encoding=true` !

I think we need to add this into doc to describe how to support a `PutRecordsRequest`.

Thanks for the pointer!
And feel free to provide such a contribution!

**Comment by hamid646** [comment]
Please review: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/pull/147
