### ISSUE TITLE
Kinesis Binder with AWS STS Assume Role Session Credentials

### ISSUE THREAD

**Issue by jwalkernz** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#169]
Is it possible to have multiple kinesis bindings with different STS assume role credentidals?

I have configured spring cloud stream kinesisProxyCredentialsProvider bean with a single assume role but I need a number of different roles for different kinesis data streams.

Thanks

**Comment by jwalkernz** [comment]
@Bean
  @Primary
  public AWSCredentialsProvider kinesisProxyCredentialsProvider() {
    final AWSSecurityTokenService stsClient =
        AWSSecurityTokenServiceClientBuilder.standard()
            .withRegion(region)
            .withCredentials(awsCredentialsProvider)
            .build();
    return new STSAssumeRoleSessionCredentialsProvider.Builder(awsAssumeRoleARN, SESSION_NAME)
        .withStsClient(stsClient)
        .build();
  }

**Comment by artembilan** [comment]
That's one could be achieve with `multi-binder` support in Spring Cloud Stream: https://docs.spring.io/spring-cloud-stream/docs/3.1.3/reference/html/spring-cloud-stream.html#multiple-binders.

While it doesn't say about different ENV for the same binder, but that's not relevant: you can have several Kinesis binder instances configured to their specific requirements per binding.

Saying that I would suggest to revise your solution from the Microservice perspective: have a single functionality per your service and do it right: better to keep different bindings in different apps with their own configuration.
This way you won't have a headache how to configure that multi-binder specifics and will have a better support in the future.

Closing this one as a `Question` since there is really nothing more we can do in this project.

Thanks for understanding!

**Comment by jwalkernz** [comment]
Hi Artem, thanks for the response, I have tried creating and configuring a custom KinesisBinderConfiguration but get error with data stream, also tried @Bean public BinderCustomizer binderCustomizer() {} but cannot get access to the aws credentials to set the STS to assume role provider.

**Comment by artembilan** [comment]
I'm not familiar with STS and asssume role provider, but probably your credentials provider has to be declared as a bean in the specific custom configuration which has to be visible only for that particular binder instance.
See this sample for more info: https://github.com/spring-cloud/spring-cloud-stream-samples/tree/main/multi-binder-samples/multi-binder-two-kafka-clusters

**Comment by jwalkernz** [comment]
I added binder config, custom configurators and spring.binders file and it works great;  each binder uses a different aws sts assume role to connect to across account kinesis data streams. Thanks for your help.
