### ISSUE TITLE
source/sink/processor examples using this binder

### ISSUE THREAD

**Issue by komushi** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#3]
just a simple question. Have we have any source/sink/processor examples using this binder?

**Comment by artembilan** [comment]
Unfortunately this project isn't mature yet. There is no actual "hard" functionality.
So, since it isn't worked, there is no samples yet.

Although I assume the source/sink/processor sample should be absolutely similar to what we have with Rabbit or Kafka except the Kinesis-specific Binder options.

I'm keeping this issue open until we really implement requested sample.

Thank you for the interest to the project!

**Comment by JacobASeverson** [comment]
Hi @komushi, I have a project with source/sink that I'm using while working on a PR for stream auto-creation https://github.com/JacobASeverson/stream-example-kinesis

There's a few issues to work through before the project is fully functional but you can send/receive payloads through a manually created stream.

**Comment by komushi** [comment]
@artembilan 

Thanks. I created a series of demos and reference architectures based on springxd and spring cloud stream  when I was working at this company. Now I have customers who will be pretty interested in a mature stream solution and also would like to utilize the aws managed services - to maintain a rabbitmq or kafka cluster is not preferred.

Thanks for your response and please keep it open.

Thanks,
Lei Xu

**Comment by komushi** [comment]
@JacobASeverson 

This is really exciting. Let me play with it soon.

Thanks

Thanks a lot

**Comment by oatesp** [comment]
I have a basic example application here https://github.com/oatesp/KinesisProducer/tree/master

**Comment by artembilan** [comment]
@JacobASeverson,
@oatesp ,

Thank you very much for such a great work done for this project!
What do you think if we "steal" your samples to our centralized repository?

@sabbyanandan ,
would you mind to share information where do we keep samples for binders and if there is some guideline how to contribute them?

I think we've done already enough work here to go ahead to the final stage to close this issue properly after merging samples. If @JacobASeverson and @oatesp don't mind of course. Otherwise I think we should work out something like links to their repositories.

**Comment by oatesp** [comment]
Please do take the sample, I would have put it in this repository but wasn't sure the best directory layout.

**Comment by artembilan** [comment]
Thanks, @oatesp !

Well, neither I do the proper way. That's why I'm asking @sabbyanandan for guidance.

**Comment by sabbyanandan** [comment]
Hi, @artembilan. This is great work indeed! If we can submit them as reference apps in [Spring Cloud Stream Samples](https://github.com/spring-cloud/spring-cloud-stream-samples), that'd be great. Perhaps we could create an `incubating` submodule? We don't release this project, so milestone/snapshot based reference apps could live there happily. Once the kinesis-binder graduates to GA, we can then consider moving it to the official app-starters.

**Comment by artembilan** [comment]
Great! Thank you @sabbyanandan !
I indeed have missed that repo somehow...

Well, I don't think that we should worry somehow about `incubating` or `app-starters`. These are samples how to use Kinesis Binder in the Stream App - nothing more!

So, @oatesp , feel free to PR the `spring-cloud-stream-samples` project with your sample and mention me for some nit-picking during review 😉 

Once your PR is merged, we'll close this issue in favor of awesome work.

@JacobASeverson ,

you feel free to share your sample the same way as well.

Thank you everybody for smooth teamwork.
Looking forward for more contribution from you!

**Comment by JacobASeverson** [comment]
@artembilan Sure, I'll submit a PR later today.

**Comment by JacobASeverson** [comment]
@artembilan after looking at this further, I'm not sure where my project would fit in. Would you suggest splitting my project into 2 separate modules in `spring-cloud-stream-samples` named `kinesis-source` and `kinesis-sink`?

**Comment by oatesp** [comment]
It doesn't look like there is much consistency to the samples and no PR have been completed in a while on that project.

I've submitted my sample as is, which combines the source and sink in 1 app with a REST endpoint.

**Comment by artembilan** [comment]
@JacobASeverson ,

I don't mean to offend you but looks like @oatesp 's sample covers your code as well.
So, maybe that one is enough for the public repository and to fix this issue?

**Comment by JacobASeverson** [comment]
@artembilan That was my thought as well.
