### ISSUE TITLE
Transformer's process will get blocked once an exception being throwed

### ISSUE THREAD

**Issue by komushi** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#34]
Converting one scs Transformer which transforms string to json. Tested with rabbitmq and kafka binders.

If the input payload is null the process should be skipped but with kinesis binder the following input payloads will be blocked - no logs no matter valid or invalid input payloads.

Below is the simplified version:
```
    @Transformer(inputChannel = Processor.INPUT, outputChannel = Processor.OUTPUT)
    public Tuple transform(Message<?> message) {

        if (logger.isTraceEnabled()) {
            logger.trace(String.format("Handling message: %s", message));
        }

        Object payloadObj = message.getPayload();
        String payload = null;

        if (payloadObj instanceof String) {
            try
            {
                payload = payloadObj.toString();
            }
            catch (Exception e)
            {
                throw new MessageTransformationException(message, e.getMessage(), e);
            }
        }

        if (payload == null) {
            throw new MessageTransformationException(message, "payload empty");
        }

        Tuple tuple = null;

        tuple = TupleBuilder.tuple()
            .put("uuid", UUID.randomUUID())
            .put("payload", payload)
            .build();

        return tuple;

    }
```

**Comment by artembilan** [comment]
I think the situation is here just because we don't provide any error handling on the `KinesisMessageDrivenChannelAdapter` here. I think I see some simple fix on the matter so far, but at the same time you can consider handle that exception with the `adviceChain` on that `@Transformer` and with something like `RequestHandlerRetryAdvice` or `ExpressionEvaluatingRequestHandlerAdvice` to suppress exception propagation to the `KinesisMessageDrivenChannelAdapter` level. 

Meanwhile I see where is a deadlock. `KinesisMessageDrivenChannelAdapter` doesn't catch any exception in its `processTask()` and therefore in case of exception from the `processRecords()` we don't call `ShardConsumer.this.task = null;` and therefore never come back to dispatching state.

Will fix that part soon as well.

I will close this issue when the commit with the `errorChannel` population comes to the `master`.

**Comment by komushi** [comment]
Thanks a lot.

Wondering at which release/version this might be fixed.

**Comment by artembilan** [comment]
See #32. We need all those versions to be released to let us finally release M1.

In my best feeling this is going to a part of the next Spring Cloud Stream release train.
