### ISSUE TITLE
no flag to turn off auto creation of kinesis stream in case it doesn't exist.

### ISSUE THREAD

**Issue by vikrantch-hk** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#37]
binder is creating new stream automatically if stream doesn't exist. There is a flag in Kafka binder to stop auto creation of kafka topics. Please provide same kind of flag in kinesis binder also.

In Kafka binder we have
pring.cloud.stream.kafka.binder.autoCreateTopics

logs 
org.springframework.context.annotation.AnnotationConfigApplicationContext@237bdbcb: startup date [Fri Feb 16 23:53:26 IST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@68b32e3e
2018-02-16 23:53:27.765  INFO 7552 --- [main] o.s.c.s.b.k.p.KinesisStreamProvisioner   : Using Kinesis stream for outbound: output
2018-02-16 23:53:28.140  INFO 7552 --- [main] o.s.c.s.b.k.p.KinesisStreamProvisioner   : Stream 'output' not found. Create one...
2018-02-16 23:53:48.878  INFO 7552 --- [main] o.s.integration.channel.DirectChannel    : Channel 'application.output' has 1 subscrib

**Comment by JacobASeverson** [comment]
Hi @vikrantch-hk, see https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/pull/5#discussion_r129602089 for the discussion about that property.

**Comment by vikrantch-hk** [comment]
@JacobASeverson Hi can you please help me with flag name, I am not seeing any property like autoCreateStreams in kinesis stream binder

**Comment by artembilan** [comment]
@JacobASeverson ,

Thank you very much for the answer!

I was on PTO, so that was too hard to find an appropriate discussion we had with you on the matter.

@vikrantch-hk ,

Please, read the discussion there. We definitely went way do not support such a flag in Kinesis Binder.

This is copy/paste of that discussion if it is hard for you to find it:

> artembilan on Jul 26, 2017 Member

> Why do we need this option, BTW?

> What will happen if we don't have a stream in the Kinesis and autoCreateStreams == false?
How is it going work then?

> IMO we don't need this option and should return ProducerDestination/ConsumerDestination as it is described in the Kinesis or create otherwise. The state when we don't have and don't create seems for me insufficient.

> Thanks


> @JacobASeverson
JacobASeverson on Jul 27, 2017 Contributor

>Hi @artembilan , Thanks for taking the time to review! This implementation is heavily influenced by the Kafka binder - there are a handful of things I questioned myself, but when in doubt I tried to stay consistent with that project.

> autoCreateStreams is modeled after the Kafka binder's autoCreateTopics property detailed here. I also don't see much value in allowing the binder to fail when there's no existing stream and autoCreateStreams=false, but it is consistent with the Kafka binder's handling.

> Let me know if it's preferable to refactor that property out and default the provisioner to create/update on startup - I'd be all for it.

> @artembilan
artembilan on Jul 27, 2017 Member

> Great, @JacobASeverson !

> I'm glad that we with you are in the same boat.

> I wasn't involved in the Kafka Binder design, so can't say what is the point to allow to have that behavior there. Maybe main point that Kafka allows to create topic on demand by its nature: http://kafka.apache.org/documentation.html#configuration. See auto.create.topics.enable. Therefore even if we configure there autoCreateStreams=false and no topic on the Broker in advance, it will be created automatically by the first interaction with it - consume or produce.

> Here in Kinesis we don't have such a luxury, hence the confuse with this option.

> So, we should create stream in the Kinesis if it doesn't exist unconditionally.
Although I guess we could have updateShardCount = true/false option and call an appropriate Kinesis method if provides shards count isn't equal to the existing in stream. Otherwise we just return the stream as is overriding provided partitions options.


If there is really some use-case that you wouldn't like to create a stream by the application when it doesn't exist, you should consider to restrict such a functionality using permissions on the AWS service for the user. 

Out of topic: Please, study how to comment here on GH also. It's hard to read plain text for exceptions.


*Closed as Works as Designed*
