### ISSUE TITLE
Java Generics with event object casting issue...

### ISSUE THREAD

**Issue by sidath80** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#54]
Hi Team,
I am  sending the Event  to the kinesis stream with following as an example.
```  
Event<T> implements Serializable {
	private UUID id;
	private T subject;
	private String type;
	private String originator;

       public Event(T subject, String type, String originator) {
		this.subject = subject;
		this.type = type;
		this.originator = originator;
	}
}
```

From producer i am sending with this  event with following information and it is successful.
```
  private StreamProcessor orderOut;

  EventDTO  dto=new EventDTO();
  dto.setData("hi");
  Event <EventDTO> event=new Event<>(dto, "type", "originator");

  orderOut.ordersOut().send(new GenericMessage<>(event));

```

From my listener   I am trying to receive it and it is successful. 

```
        @StreamListener(StreamProcessor.INPUT)
	public void receive(Event <EventDTO> event) {
       
           EventDTO dto=(EventDTO)event.getSubject();
        }
```

But giving following ERROR when try to cast my Event subject field which is generics filed  
```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.abc.xyz.EventDTO
```

Any help will be highly appreciate. 
Thank you.
Sidath

**Comment by artembilan** [comment]
This fully is not related to this Binder implementation or Kinesis per se.

The real problem that you are missing the fact that content conversion is based on the JSON by default since Spring Cloud Stream `2.0`: https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RELEASE/reference/htmlsingle/#content-type-management

So, what you see with that `LinkedHashMap` is exactly a limitation what Jackson can do for you serializing your `Event<EventDTO>` POJO on the producer side.

What you can do is something like provide your own (de)serialization mechanism (e.g. standard Java Serialization System) and override that default JSON handling. 

You can find such an info in the mentioned docs.

Another variant that you can provide a *Default Typing* configuration for the Jackson `ObjectMapper` bean and your nested generic type will save its info in the target JSON to be properly deserializied with similar `ObjectMapper` on the consumer side. 

More info is here: https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization.

And also see `org.springframework.integration.support.json.JacksonJsonUtils.messagingAwareMapper()`.

Nevertheless there is no issues from this Binder perspective. Therefore I close this as `invalid`.

Please, consider in the future ask questions on StackOverflow or any other relevant forums. And also, please, be specific in your issue do not share it in the domain where there is no issue. 

Thanks for understanding.
