### ISSUE TITLE
Documentation misses out, which aws permissions are required

### ISSUE THREAD

**Issue by christianfinckler1212** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#57]
Hello,
I currently managed to get it partly working. But I have to add one permission at a time, test it and add the next access right.

Therefore it would really help, if you would write, which services are used and which permissions are required. I am currently aware of these:
"kinesis:PutRecord",
"kinesis:PutRecords",
"kinesis:DescribeStream",
"kinesis:GetRecords",
"dynamodb:DescribeTable"

Thank you very much

**Comment by artembilan** [comment]
I think this is really good improvement.

Contribution is welcome though!

Thanks

**Comment by naxhh** [comment]
Hi, we where using camel with spring boot 1 and moved to this at spring boot 2. We also found the lack of documentation very discouraging to use this project. But we really wanted the lock and consumer groups features. Also only using spring-boot-stream instead of mixing a lot of libraries.

Our approach was to use an admin credentials to create the resources and then use a "user" policies for normal usage.

We found out some strange behaviours, like if the app doesn't have DescribeTable for dynamodb it will try to create the table, instead of telling you it doesn't have the credentials...
Also if it doesn't have permissions for the metadata store it will not read anything, but it will not fail also.

In our experience, it was very useful to check the code of the deps of this project:
https://github.com/spring-projects/spring-integration-aws and https://github.com/awslabs/dynamodb-lock-client to understand what was really happening.

With the following policy it works fine for us, it's a bit open regarding kinesis permissions but if you want to refine it you'll need to spend some time with trial and error.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "dynamodb:PutItem",
                "dynamodb:DescribeTable",
                "dynamodb:GetItem",
                "kinesis:*",
                "dynamodb:UpdateItem"
            ],
            "Resource": [
                "arn:aws:kinesis:<region>:<accountID>:stream/<stream_name>",
                "arn:aws:dynamodb:<region>:<accountID>:table/<metadatastore-table>",
                "arn:aws:dynamodb:<region>:<accountID>:table/<lock-table>"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "kinesis:ListStreams",
                "kinesis:EnableEnhancedMonitoring",
                "dynamodb:ListTables",
                "kinesis:ListShards",
                "kinesis:UpdateShardCount",
                "kinesis:GetRecords",
                "kinesis:DescribeLimits",
                "kinesis:ListStreamConsumers",
                "kinesis:DisableEnhancedMonitoring"
            ],
            "Resource": "*"
        }
    ]
}
```

Hope this helps someone.
What works with this:
- Find the metadata & lock tables
- Create, update and get items from them
- Get kinesis events

Also we have the autoCreate at off always

**Comment by artembilan** [comment]
Unfortunately, I'm not familiar with AWS permissions and their setting options.
@naxhh , thank you for sharing your experience, but such a config doesn't look like something generic which we could include into our docs as an instruction to go for everybody else.

I'll fully open for any suggestions and PR with more details what and how should be configured from AWS side to achieve a goal of the target project.

Thanks for understanding!

**Comment by naxhh** [comment]
Sure. I was not expecting anything from this comment, just to throw some light on what permissions may be required. This works for us and we haven't found any problems on production.
But refining to the exact permissions required is too much hassle, but maybe it's a good starting point for someone else

**Comment by artembilan** [comment]
Correct. We can fix that on demand.
I just worry that you sample config is not so generic, so would be great to formalize it somehow and contribute into the Docs for everybody else.

Thanks

**Comment by naxhh** [comment]
Idk what you mean about being generic.

If is because of this part:

```
                "arn:aws:kinesis:<region>:<accountID>:stream/<stream_name>",
                "arn:aws:dynamodb:<region>:<accountID>:table/<metadatastore-table>",
                "arn:aws:dynamodb:<region>:<accountID>:table/<lock-table>"
```

the ARN (id of the resource) depends on the region you have created it and also in your account.
So you can't make a simple copy&paste rule out of that.

If you mean it because of how we created the first resources. I would guess you need to add `dynamodb:CreateTable` permission in the second block.

But in our specific case we didn't want to allow this service to create any table in production by it's own... so we left that out

**Comment by artembilan** [comment]
Well, my point is: give me something I can add to doc to be useful for everybody and as generic as possible.

My problem that I don't know those AWS permissions set functionality and it is slightly out of this project scope, so, I don't know from where to start.
Therefore my request for some simple PR from your side which could be incorporated to docs of this project as a side not what should be done on the AWS side.

Thanks for understanding.
