### ISSUE TITLE
how to disable MetadataStore

### ISSUE THREAD

**Issue by yezhoujie** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#93]
I'm using kinesis only as a producer, and I have no authority to dynamodb, how to disable  MetadataStore, I don't want to create a dynamodb table when the program starts, thanks

**Comment by artembilan** [comment]
There is no a configuration properties level way right now to disable those beans to be created.

The only way I see is like have a custom `@Configuration` class like this:

```
@Configuration
public class MockKinesisConsumerConfiguration {

               @Bean
		public AmazonDynamoDBAsync dynamoDB() {
			return null;
		}

		@Bean
		public ConcurrentMetadataStore kinesisCheckpointStore() {
			return new SimpleMetadataStore();
		}

		@Bean
		public LockRegistry dynamoDBLockRegistry() {
			return new DefaultLockRegistry();
		}

}
```

This way we allow a `@ConditionalOnMissingBean` to be positive and override all the required beans to their in-memory implementations: luckily you are not going to use that at all in your Sink Microservice.

But at the same time I'm looking for some out-of-the-box solution how do not create those Source-related beans  when we are only as a Sink...

**Comment by ywilkof** [comment]
@yezhoujie I had the same issue (using spring-cloud-stream-binder-kinesis 1.1.0-RELEASE). Didn't want to create any dynamoDb tables or give permissions to them.
Upgrading to spring-cloud-stream-binder-kinesis 1.2.0-RELEASE solved it. When upgrading to this version you need to also upgrade the aws java sdk (I'm using 1.11.510), otherwise you will get nasty ClassNotFound exception.
